[project]
name = "microdi"
version = "0.1.0"
description = "Micro Dependency Injection Framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "mypy",
    "isort",
    "flake8",
]
